from enum import Enum


class DomDetectionCase(Enum):
    HIGH_RISK_TAG = 1,
    FORM_ACTION_CROSS_DOMAIN = 2
    FORM_ACTION_MAILTO = 3,
    PAGE_TITLE_MATCHING = 4,
    PHISHING_EXTERNAL_LINK_CHECK = 5,
    MIMIC_LOGIN_SITE = 6,
    OBFUSCATION_JAVASCRIPT = 8,
    MIMIC_LOGIN_STRUCTURE = 9,
    CHECK_PAGE_SIGNALS = 10,
    MULTIPLE_SUBMIT = 11,
    BODY_TEXT_TAG_COUNT = 12,
    TECHNOLOGIES_COUNT = 13
 
    
